// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://ezdpmpwnqnizbveamicd.supabase.co';
const SUPABASE_PUBLISHABLE_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6ZHBtcHducW5pemJ2ZWFtaWNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MTUxMTgsImV4cCI6MjA2NDI5MTExOH0.dMxDgYAhINZTJhK7qGMNecZEIKAS_B2HSGWv9e5d088';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);
