name: Secret Scan

on: [push, pull_request]

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Scan for secrets
        run: |
          PATTERNS='(_API_KEY|APIKEY|apiKey|apikey|SECRET|secret|Token|token)[^\\n]*=|sk-[a-zA-Z0-9]{20,}|eyJ[a-zA-Z0-9_-]{20,}\\.[a-zA-Z0-9_-]{20,}\\.[a-zA-Z0-9_-]{20,}'
          if grep -rE -i "$PATTERNS" . --exclude-dir={.git,node_modules,.taskmaster,.husky,.next,.vercel,.cache,dist,build,coverage}; then
            echo "❌ Potential secret/API key detected in codebase. Please remove before merging."
            exit 1
          fi